// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLSbrOp2O5PdjRbF9x5LccNVViDkIp9Yo',
    appId: '1:63028058946:web:523fb24a1f2ddf898b86db',
    messagingSenderId: '63028058946',
    projectId: 'shoopink-c9cb0',
    authDomain: 'shoopink-c9cb0.firebaseapp.com',
    storageBucket: 'shoopink-c9cb0.appspot.com',
    measurementId: 'G-GSM736WND4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADRATS9ZLAq-EZN-cJIopexQmrPiFBrc4',
    appId: '1:63028058946:android:c311dd8aa2004f2d8b86db',
    messagingSenderId: '63028058946',
    projectId: 'shoopink-c9cb0',
    storageBucket: 'shoopink-c9cb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC46jugA3LIH-y9i9cK0wJJpXDsDFVOvFY',
    appId: '1:63028058946:ios:e035de737806fafd8b86db',
    messagingSenderId: '63028058946',
    projectId: 'shoopink-c9cb0',
    storageBucket: 'shoopink-c9cb0.appspot.com',
    iosBundleId: 'com.example.groceryApp',
  );
}
